# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "vm1" do |vm1|
    vm1.vm.hostname = "vm1"
    vm1.vm.box = "debian/buster64"
    vm1.vm.network "private_network", ip: "192.168.10.1"
  end

  config.vm.define "vm2" do |vm2|
    vm2.vm.hostname = "vm2"
    vm2.vm.box = "debian/buster64"
    vm2.vm.network "private_network", ip: "192.168.10.2"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
    vb.name = $name
    vb.cpus = 1
  end

end
